<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Description>OpenStack Swift client for .NET 9.0</Description>
    <VersionPrefix>9.0.0-beta</VersionPrefix>
    <Authors>Cristi Pufu;Stefan Prodan</Authors>
    <AssemblyName>SwiftClient</AssemblyName>
    <PackageId>SwiftClient</PackageId>
    <PackageTags>OpenStack;Swift</PackageTags>
    <PackageProjectUrl>https://github.com/vtfuture/SwiftClient</PackageProjectUrl>
    <PackageLicenseUrl>http://opensource.org/licenses/MIT</PackageLicenseUrl>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/vtfuture/SwiftClient</RepositoryUrl>
    <GenerateRuntimeConfigurationFiles>true</GenerateRuntimeConfigurationFiles>
    <GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
    <GenerateAssemblyCompanyAttribute>false</GenerateAssemblyCompanyAttribute>
    <GenerateAssemblyProductAttribute>false</GenerateAssemblyProductAttribute>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.0" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <PlatformTargets>x64,arm64</PlatformTargets>
  </PropertyGroup>

  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <PlatformTargets>x64,arm64</PlatformTargets>
  </PropertyGroup>

</Project>
